name: search
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  eva_icons_flutter: ^3.1.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  rxdart: ^0.27.3
  flutter:
    sdk: flutter
  core:
    path: ../core
  movie:
    path: ../movie
  tv:
    path: ../tv

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.0.3


flutter:

