name: tv
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  
dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter
  core:
    path: ../core
  local_db:
    path: ../local_db
  watchlist:
    path: ../watchlist
  readmore: ^2.1.0
  dartz: ^0.10.0-nullsafety.2
  flutter_rating_bar: ^4.0.0
  equatable: ^2.0.2
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3
  cached_network_image: ^3.0.0
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0

flutter:
