// Mocks generated by Mockito 5.1.0 from annotations
// in search/test/domain/usecases/search_tvs_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:core/common/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv/domain/entities/tv.dart' as _i6;
import 'package:tv/domain/entities/tv_detail.dart' as _i7;
import 'package:tv/domain/entities/tv_season.dart' as _i8;
import 'package:tv/domain/repositories/tv_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i3.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getOnTheAirTvs() =>
      (super.noSuchMethod(Invocation.method(#getOnTheAirTvs, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getPopularTvs() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvs, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getTopRatedTvs() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvs, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, _i7.TvDetail>>.value(
                  _FakeEither_0<_i5.Failure, _i7.TvDetail>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i7.TvDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> searchTv(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTv, [query]),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlistTv(
          _i7.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlistTv, [tv]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWatchlistTv(
          _i7.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistTv, [tv]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<bool> isTvAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isTvAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getWatchlistTvs() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvs, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.TvSeason>> getTvSeason(
          int? tvId, int? seasonNumber) =>
      (super.noSuchMethod(Invocation.method(#getTvSeason, [tvId, seasonNumber]),
              returnValue: Future<_i2.Either<_i5.Failure, _i8.TvSeason>>.value(
                  _FakeEither_0<_i5.Failure, _i8.TvSeason>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i8.TvSeason>>);
}
